//  Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: ideal-template-projects-and-workflow
:page-layout: guide-multipane
:page-duration: 0 minutes
:page-releasedate: 2020-12-31
:page-description: Describe the ideal template projects for Open Liberty
:guide-author: Open Liberty
:page-tags: ['MicroProfile', 'Jakarta EE', 'Microservices']
:page-related-guides: [ ]
:page-permalink: /guides/{projectid}
:imagesdir: /img/guide/{projectid}
:page-seo-title: Describe the ideal template projects for Open Liberty
:page-seo-description: Describe all different ideal template projects for developing Cloud Native application with Open Liberty
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Describe all different ideal template projects for developing Cloud Native application with Open Liberty

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].   

Describe all different ideal template projects for developing Cloud Native application with Open Liberty.

== Basic ideal project

Descibe and explain each required file for the basic ideal project.

=== Maven configuration file

//File 0
pom.xml
[source, Text, linenums, role='code_column hide_tags=copyright']
----
include::basic-hotspot/pom.xml[]
----

Users will update the [hotspot=groudId file=0]`groupId`, [hotspot=artifactId file=0]`artifactId`, and [hotspot=version file=0]`version`.

* To be confirm

The project is targeted to package the microserive as a [hotspot=packaging file=0]`war` file.

* To be confirm

Currently, we define [hotspot=pluginVersions file=0]`<version.*/>` properties for the plugin version.

* it is necessary?
* if do that, why not the `<dependency/>`?

We define [hotspot=libertyProperties file=0]`ports` properties for the server and [hotspot=ports file=0]`test`, so that both can pick up the same ports if users change them.

* To be confirm

We define the 2 provided dependencies: [hotspot=jakartaDependency file=0]`jakartaee` and [hotspot=microprofileDependency file=0]`microprofile`.

* To be confirm

Assume to use MST, so we define those [hotspot=testDependencies file=0]`test` dependencies.

* To be confirm

We define [hotspot=finalName file=0]`<finalName/>` as the [hotspot=artifactId file=0]`artifactId`.

* To be confirm

=== Liberty configuration file

== Use the Liberty Development Mode to develop microservice

== Change the server port

== Build docker image
* When build docker image, should the artifacts be from `src` or `target`?

== Run docker image