//  Copyright (c) 2020 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: ideal-template-projects-and-workflow
:page-layout: guide-multipane
:page-duration: 0 minutes
:page-releasedate: 2020-12-31
:page-description: Describe the ideal template projects for Open Liberty
:guide-author: Open Liberty
:page-tags: ['MicroProfile', 'Jakarta EE', 'Microservices']
:page-related-guides: [ ]
:page-permalink: /guides/{projectid}
:imagesdir: /img/guide/{projectid}
:page-seo-title: Describe the ideal template projects for Open Liberty
:page-seo-description: Describe all different ideal template projects for developing Cloud Native application with Open Liberty
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Describe all different ideal template projects for developing Cloud Native application with Open Liberty

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].   

Describe all different ideal template projects for developing Cloud Native application with Open Liberty.

== Basic ideal template project

Descibe and explain each required file for the basic ideal template project.

> Assume that the project is a simple RESTful microservice by using MicroProfile features.

---

=== Maven configuration file

// File 0
pom.xml
[source, XML, linenums, role='code_column'] 
----
include::basic-hotspot/pom.xml[]
----

[role="no_copy"]
----
pom.xml
----

(To be confirmed) Users will update the [hotspot=groudId file=0]`groupId`, [hotspot=artifactId file=0]`artifactId`, and [hotspot=version file=0]`version`.

> ~ what should the `groupId` be? +
> ~ what should the `artifactId` be? +
> ~ assume that version is `1.0-SNAPSHOT`

(To be confirmed) The project is targeted to package the microserive as a [hotspot=packaging file=0]`war` file.

(To be confirmed) Currently, we define [hotspot=pluginVersions file=0]`<version.*/>` properties for the plugin version.

> is it necessary? +
> if yes, why not the `<dependency/>`? +
> suggest not need to do that

(To be confirmed) We define [hotspot=libertyProperties file=0]`ports` properties for the server and [hotspot=ports file=0]`test`, so that both can pick up the same ports if users change them.

(To be confirmed) We define the 2 provided dependencies: [hotspot=jakartaDependency file=0]`jakartaee` and [hotspot=microprofileDependency file=0]`microprofile`.

(To be confirmed) Assume to use Microshed Testing (MST), so we define those [hotspot=testDependencies file=0]`test` dependencies.

(To be confirmed) We define [hotspot=finalName file=0]`<finalName/>` as the [hotspot=artifactId file=0]`artifactId`.

---

=== Gradle configuration file

[role="no_copy"]
----
build.gradle and settings.gradle
----

> Should include Gradle project?

---

=== Liberty server configuration file

// File 0
pom.xml
[source, XML, linenums, role='code_column'] 
----
include::basic-hotspot/pom.xml[]
----

// File 1
server.xml
[source, XML, linenums, role='code_column'] 
----
include::basic-hotspot/src/main/liberty/config/server.xml[]
----

[role="no_copy"]
----
src/main/liberty/config/server.xml
----

(To be confirmed) Users will update the [hotspot=1 file=1]`description`

(To be confirmed) The minimal set of [hotspot=featureManager file=1]`features` are: `jaxrs-2.1`, ...

> what should the minimal set of features be? +
> Should include `mpHealth` feature?

(To be confirmed) The [hotspot=httpEndpoint file=1]`httpEndpoint` ports are defined by the `defaultValue` of the [hotspot=httpPort file=1]`default.http.port` and [hotspot=httpsPort file=1]`default.http.port` variables. They can be overridden through the [hotspot=httpPortProperties file=0]`pom.xml`.

(To be confirmed) The webApplication [hotspot=webApplication file=1]`location` should be [hotspot=artifactId file=0]`${artifactId}.war`. The [hotspot=webApplication file=1]`contextRoot` is defined by the [hotspot=appContextRoot file=1]`defaultValue` of the `app.context.root` variable. It can be overridden through the [hotspot=contextRootProperty file=0]`pom.xml`.

> Should externalize the context root?

---

=== Application class

[role="no_copy"]
----
src/main/java/io/openliberty/templates/basic/SimpleRestApplication.java
----

---

=== Endpoint class

[role="no_copy"]
----
src/main/java/io/openliberty/templates/basic/SimpleRestEndpoint.java 
----

---

=== Unit Test

---

=== Integration Test


---

=== Dockerfile


== Use the Liberty Development Mode to develop microservice

== Change the server port

== Build docker image
* When build docker image, should the artifacts be from `src` or `target`?

== Run docker image